---
#https://blog.benoitblanchon.fr/github-action-run-ssh-commands/

name: CI
on: [push, pull_request]
jobs:
  # test:
  #   ...
  deploy:
    name: "Deploy to staging"
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    # needs: test
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "First two characters of SSH_KEY: ${SSH_KEY:0:8}"
          echo "First two characters of SSH_KEY: ${SSH_USER:0:20}"
          echo "First two characters of SSH_KEY: ${SSH_HOST:0:20}"
          echo "$SSH_KEY" > ~/.ssh/staging.key
          echo ""
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Check out the source
        run: ssh staging 'cd my-application && git fetch && git reset --hard origin/master'
