---
#https://blog.benoitblanchon.fr/github-action-run-ssh-commands/

name: CI
on: [push, pull_request]
jobs:
  # test:
  #   ...
  deploy:
    name: "Deploy to staging"
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    # needs: test
    steps:
      - name: Configure SSH
        run: |
          ssh -i {{secret.SSH_PRIVATE_KEY}} {{secrets.SSH_USER}}@{{secrets.SSH_HOST}}
