---
#https://blog.benoitblanchon.fr/github-action-run-ssh-commands/

name: CI
on: [push, pull_request]
jobs:
  # test:
  #   ...
  deploy:
    name: "Deploy to staging"
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    # needs: test
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/gh
          chmod 600 ~/.ssh/gh
          ssh -i ~/.ssh/gh {{secrets.SSH_USER}}@{{secrets.SSH_HOST}}
