---
#https://blog.benoitblanchon.fr/github-action-run-ssh-commands/

name: CI
on: [push, pull_request]
jobs:
  # test:
  #   ...
  deploy:
    name: "Deploy to staging"
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    # needs: test
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "First two characters of SSH_KEY: ${SSH_KEY:0:25}"
          echo "First two characters of SSH_KEY: ${SSH_USER}"
          echo "First two characters of SSH_KEY: ${SSH_HOST}"
          echo "$SSH_KEY" > ~/.ssh/staging.key
          echo ""
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host home
            HostName $SSH_HOST
            User $SSH_USER
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Check out the source
        run: ssh home 'echo "test"'
