---
#https://blog.benoitblanchon.fr/github-action-run-ssh-commands/

---
name: CI
on: [push, pull_request]
jobs:
  test:
    name: Run Vitest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Run Linter
        run: npm run lint

  deploy:
    name: "Deploy to staging"
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: test
    steps:
      - name: ls -a via ssh
        run: echo "test"